/**
 * One-time offline generator: finds real Matter.js physics seeds (via
 * physics.ts - the exact same module the browser uses) that settle in each
 * possible (rows, slot_index) bin, and writes them to plinkoSeedTable.ts.
 *
 * Why this exists: a genuine physics simulation is chaotic, so there's no
 * way to make it *always* land on an arbitrary server-chosen slot without
 * either visibly steering it or brute-force searching for a seed that
 * naturally gets there. Searching live, per round, is too slow for common
 * (center) outcomes - see the plan doc for the empirical numbers. Searching
 * once, offline, with a large attempt budget, and shipping a small lookup
 * table costs nothing at runtime.
 *
 * Run with: npx tsx scripts/generate-plinko-seeds.ts
 */
import fs from 'fs';
import path from 'path';
import { ROWS_OPTIONS, simulateToSettledSlot } from '../src/components/games/plinko/physics';

const SEEDS_PER_BIN = 5;
const BASE_ATTEMPTS = 20000;
const EXTRA_BATCH = 20000;
const MAX_EXTRA_BATCHES = 10; // hard ceiling per row count: up to 220,000 attempts

function generateForRows(rows: number): Record<number, number[]> {
    const buckets: Record<number, number[]> = {};
    for (let slot = 0; slot <= rows; slot += 1) buckets[slot] = [];

    let seed = 1;
    let attempts = 0;

    function runBatch(count: number) {
        for (let i = 0; i < count; i += 1) {
            const slot = simulateToSettledSlot(rows, seed);
            if (buckets[slot].length < SEEDS_PER_BIN) buckets[slot].push(seed);
            seed += 1;
            attempts += 1;
        }
    }

    const t0 = Date.now();
    runBatch(BASE_ATTEMPTS);

    let extraBatches = 0;
    while (Object.values(buckets).some((arr) => arr.length === 0) && extraBatches < MAX_EXTRA_BATCHES) {
        runBatch(EXTRA_BATCH);
        extraBatches += 1;
        const stillEmpty = Object.entries(buckets).filter(([, arr]) => arr.length === 0).map(([s]) => s);
        console.log(`  rows=${rows}: extra batch ${extraBatches} done (${attempts} total attempts), still empty: ${stillEmpty.join(',') || 'none'}`);
    }

    const empty = Object.entries(buckets).filter(([, arr]) => arr.length === 0).map(([s]) => s);
    if (empty.length > 0) {
        throw new Error(`rows=${rows}: no seed found for slots [${empty.join(', ')}] after ${attempts} attempts (${MAX_EXTRA_BATCHES} extra batches exhausted)`);
    }

    const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
    console.log(`rows=${rows}: done in ${elapsed}s, ${attempts} attempts. Coverage: ${Object.entries(buckets).map(([s, a]) => `${s}:${a.length}`).join(' ')}`);
    return buckets;
}

const table: Record<number, Record<number, number[]>> = {};
for (const rows of ROWS_OPTIONS) {
    table[rows] = generateForRows(rows);
}

const outPath = path.join(__dirname, '../src/components/games/plinko/plinkoSeedTable.ts');
const content = `// AUTO-GENERATED by scripts/generate-plinko-seeds.ts - do not hand-edit.
// Maps rows -> slot_index -> a small pool of verified physics seeds that,
// when replayed through physics.ts's exact board/ball setup, settle in that
// exact bin. Regenerate with: npx tsx scripts/generate-plinko-seeds.ts

export const PLINKO_SEED_TABLE: Record<number, Record<number, number[]>> = ${JSON.stringify(table, null, 4)};
`;
fs.writeFileSync(outPath, content);
console.log(`\nWrote ${outPath}`);
