// AUTO-GENERATED by scripts/generate-plinko-seeds.ts - do not hand-edit.
// Maps rows -> slot_index -> a small pool of verified physics seeds that,
// when replayed through physics.ts's exact board/ball setup, settle in that
// exact bin. Regenerate with: npx tsx scripts/generate-plinko-seeds.ts

export const PLINKO_SEED_TABLE: Record<number, Record<number, number[]>> = {
    "8": {
        "0": [
            3,
            13,
            23,
            26,
            29
        ],
        "1": [
            9,
            10,
            36,
            37,
            57
        ],
        "2": [
            5,
            40,
            42,
            58,
            67
        ],
        "3": [
            14,
            31,
            45,
            49,
            50
        ],
        "4": [
            1,
            7,
            20,
            44,
            59
        ],
        "5": [
            12,
            15,
            30,
            55,
            66
        ],
        "6": [
            4,
            6,
            24,
            52,
            82
        ],
        "7": [
            2,
            18,
            19,
            35,
            76
        ],
        "8": [
            8,
            11,
            16,
            17,
            21
        ]
    }
};
